name: presence
version: 1.0.0+1
publish_to: none
description: Presence Apps
environment: 
  sdk: '>=2.17.3 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: 1.20.0
  firebase_auth: 3.6.2
  cloud_firestore: 3.4.3
  firebase_storage: 10.3.4
  image_picker: 0.8.5+3
  convex_bottom_bar: 3.0.0
  intl: 0.17.0
  geolocator: 9.0.1
  geocoding: 2.0.4
  syncfusion_flutter_datepicker: 20.2.44
  flutter: 
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

dev_dependencies: 
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

