// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9Km6NSpaYx5NvyQ_9sImpCEi23iI1gQU',
    appId: '1:959077421220:web:0fb6d99ad89e03f6181631',
    messagingSenderId: '959077421220',
    projectId: 'presence-d9186',
    authDomain: 'presence-d9186.firebaseapp.com',
    storageBucket: 'presence-d9186.appspot.com',
    measurementId: 'G-DYZFG9YVX3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvBwpYtsQSTN-q7Ilz19DVnSSgHWCooTk',
    appId: '1:959077421220:android:743562d533a3cbf6181631',
    messagingSenderId: '959077421220',
    projectId: 'presence-d9186',
    storageBucket: 'presence-d9186.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1f5LeIePzoY2bt7nSUO3oC51L-gYHLp4',
    appId: '1:959077421220:ios:4ca0a74017c52f9b181631',
    messagingSenderId: '959077421220',
    projectId: 'presence-d9186',
    storageBucket: 'presence-d9186.appspot.com',
    iosClientId: '959077421220-115nnjtfthjnbqs9vjbtjovkc1q7fcv9.apps.googleusercontent.com',
    iosBundleId: 'com.putra.presence',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1f5LeIePzoY2bt7nSUO3oC51L-gYHLp4',
    appId: '1:959077421220:ios:4ca0a74017c52f9b181631',
    messagingSenderId: '959077421220',
    projectId: 'presence-d9186',
    storageBucket: 'presence-d9186.appspot.com',
    iosClientId: '959077421220-115nnjtfthjnbqs9vjbtjovkc1q7fcv9.apps.googleusercontent.com',
    iosBundleId: 'com.putra.presence',
  );
}
